### ISSUE TITLE
Feature request: Health styles/customization

### ISSUE THREAD

**Issue by xIGBClutchIx** [ReubinAuthor/ReubinsNameplates#2]
I love the addon fits perfectly with the default UI.

One feature I would love it if you could have a different style or possibly just customize the health text. The current type I want is similar to having both status texts enabled on a unit frame. So both percentage and the numerical value. 

Example: 
![tkYfVq9G](https://user-images.githubusercontent.com/975065/194913979-59a07133-2c28-4437-a64a-6e7345a914cc.png)

**Comment by ReubinAuthor** [comment]
I'll consider it, tank you :)

**Comment by ReubinAuthor** [comment]
Added health percentage in v2.0.0
